//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.19 at 02:21:08 PM CET 
//


package juliawsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for analysisPackage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="analysisPackage">
 *   &lt;complexContent>
 *     &lt;extension base="{http://service.server.web.julia.juliasoft.com/}artifact">
 *       &lt;sequence>
 *         &lt;element name="moduleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="packageMetrics" type="{http://service.server.web.julia.juliasoft.com/}projectMetrics" minOccurs="0"/>
 *         &lt;element name="type" type="{http://service.server.web.julia.juliasoft.com/}packageType"/>
 *         &lt;element name="relatedArtifact" type="{http://service.server.web.julia.juliasoft.com/}artifact" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "analysisPackage", propOrder = {
    "moduleName",
    "packageMetrics",
    "type",
    "relatedArtifact"
})
public class AnalysisPackage
    extends Artifact
{

    protected String moduleName;
    protected ProjectMetrics packageMetrics;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected PackageType type;
    protected List<Artifact> relatedArtifact;

    /**
     * Gets the value of the moduleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * Sets the value of the moduleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModuleName(String value) {
        this.moduleName = value;
    }

    /**
     * Gets the value of the packageMetrics property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectMetrics }
     *     
     */
    public ProjectMetrics getPackageMetrics() {
        return packageMetrics;
    }

    /**
     * Sets the value of the packageMetrics property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectMetrics }
     *     
     */
    public void setPackageMetrics(ProjectMetrics value) {
        this.packageMetrics = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link PackageType }
     *     
     */
    public PackageType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageType }
     *     
     */
    public void setType(PackageType value) {
        this.type = value;
    }

    /**
     * Gets the value of the relatedArtifact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedArtifact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedArtifact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Artifact }
     * 
     * 
     */
    public List<Artifact> getRelatedArtifact() {
        if (relatedArtifact == null) {
            relatedArtifact = new ArrayList<Artifact>();
        }
        return this.relatedArtifact;
    }

}
