//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.19 at 02:21:08 PM CET 
//


package juliawsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for analysisCost complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="analysisCost">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="costInLOC" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="exceedingCredits" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="showMessage" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "analysisCost", propOrder = {
    "costInLOC",
    "exceedingCredits",
    "message",
    "showMessage"
})
public class AnalysisCost {

    protected long costInLOC;
    protected boolean exceedingCredits;
    protected String message;
    protected boolean showMessage;

    /**
     * Gets the value of the costInLOC property.
     * 
     */
    public long getCostInLOC() {
        return costInLOC;
    }

    /**
     * Sets the value of the costInLOC property.
     * 
     */
    public void setCostInLOC(long value) {
        this.costInLOC = value;
    }

    /**
     * Gets the value of the exceedingCredits property.
     * 
     */
    public boolean isExceedingCredits() {
        return exceedingCredits;
    }

    /**
     * Sets the value of the exceedingCredits property.
     * 
     */
    public void setExceedingCredits(boolean value) {
        this.exceedingCredits = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the showMessage property.
     * 
     */
    public boolean isShowMessage() {
        return showMessage;
    }

    /**
     * Sets the value of the showMessage property.
     * 
     */
    public void setShowMessage(boolean value) {
        this.showMessage = value;
    }

}
