//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.19 at 02:21:08 PM CET 
//


package juliawsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for analysisExtendedStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="analysisExtendedStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="progress" type="{http://service.server.web.julia.juliasoft.com/}analysisProgress" minOccurs="0"/>
 *         &lt;element name="status" type="{http://service.server.web.julia.juliasoft.com/}analysisStatus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "analysisExtendedStatus", propOrder = {
    "progress",
    "status"
})
public class AnalysisExtendedStatus {

    protected AnalysisProgress progress;
    @XmlSchemaType(name = "string")
    protected AnalysisStatus status;

    /**
     * Gets the value of the progress property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisProgress }
     *     
     */
    public AnalysisProgress getProgress() {
        return progress;
    }

    /**
     * Sets the value of the progress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisProgress }
     *     
     */
    public void setProgress(AnalysisProgress value) {
        this.progress = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisStatus }
     *     
     */
    public AnalysisStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisStatus }
     *     
     */
    public void setStatus(AnalysisStatus value) {
        this.status = value;
    }

}
