//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.19 at 02:21:08 PM CET 
//


package juliawsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for analysisStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="analysisStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="INIT"/>
 *     &lt;enumeration value="PREPROCESSING"/>
 *     &lt;enumeration value="SUBMITTED"/>
 *     &lt;enumeration value="QUEUED"/>
 *     &lt;enumeration value="INPROGRESS"/>
 *     &lt;enumeration value="COMPLETED"/>
 *     &lt;enumeration value="TIMEDOUT"/>
 *     &lt;enumeration value="ERROR"/>
 *     &lt;enumeration value="CANCELLED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "analysisStatus")
@XmlEnum
public enum AnalysisStatus {

    INIT,
    PREPROCESSING,
    SUBMITTED,
    QUEUED,
    INPROGRESS,
    COMPLETED,
    TIMEDOUT,
    ERROR,
    CANCELLED;

    public String value() {
        return name();
    }

    public static AnalysisStatus fromValue(String v) {
        return valueOf(v);
    }

}
