//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.19 at 02:21:08 PM CET 
//


package juliawsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for analysisSpecification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="analysisSpecification">
 *   &lt;complexContent>
 *     &lt;extension base="{http://service.server.web.julia.juliasoft.com/}analysisSpecificationBase">
 *       &lt;sequence>
 *         &lt;element name="packages" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="package" type="{http://service.server.web.julia.juliasoft.com/}analysisPackage" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="options" type="{http://service.server.web.julia.juliasoft.com/}options" minOccurs="0"/>
 *         &lt;element name="checkers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="checker" type="{http://service.server.web.julia.juliasoft.com/}checker" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "analysisSpecification", propOrder = {
    "packages",
    "options",
    "checkers"
})
public class AnalysisSpecification
    extends AnalysisSpecificationBase
{

    protected AnalysisSpecification.Packages packages;
    protected Options options;
    protected AnalysisSpecification.Checkers checkers;

    /**
     * Gets the value of the packages property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisSpecification.Packages }
     *     
     */
    public AnalysisSpecification.Packages getPackages() {
        return packages;
    }

    /**
     * Sets the value of the packages property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisSpecification.Packages }
     *     
     */
    public void setPackages(AnalysisSpecification.Packages value) {
        this.packages = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link Options }
     *     
     */
    public Options getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link Options }
     *     
     */
    public void setOptions(Options value) {
        this.options = value;
    }

    /**
     * Gets the value of the checkers property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisSpecification.Checkers }
     *     
     */
    public AnalysisSpecification.Checkers getCheckers() {
        return checkers;
    }

    /**
     * Sets the value of the checkers property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisSpecification.Checkers }
     *     
     */
    public void setCheckers(AnalysisSpecification.Checkers value) {
        this.checkers = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="checker" type="{http://service.server.web.julia.juliasoft.com/}checker" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "checker"
    })
    public static class Checkers {

        @XmlElement(required = true)
        protected List<Checker> checker;

        /**
         * Gets the value of the checker property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the checker property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getChecker().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Checker }
         * 
         * 
         */
        public List<Checker> getChecker() {
            if (checker == null) {
                checker = new ArrayList<Checker>();
            }
            return this.checker;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="package" type="{http://service.server.web.julia.juliasoft.com/}analysisPackage" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_package"
    })
    public static class Packages {

        @XmlElement(name = "package")
        protected List<AnalysisPackage> _package;

        /**
         * Gets the value of the package property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the package property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPackage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AnalysisPackage }
         * 
         * 
         */
        public List<AnalysisPackage> getPackage() {
            if (_package == null) {
                _package = new ArrayList<AnalysisPackage>();
            }
            return this._package;
        }

    }

}
