//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.19 at 02:21:08 PM CET 
//


package juliawsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for analysisReportResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="analysisReportResult">
 *   &lt;complexContent>
 *     &lt;extension base="{http://service.server.web.julia.juliasoft.com/}analysisResult">
 *       &lt;sequence>
 *         &lt;element name="analysisSpecification" type="{http://service.server.web.julia.juliasoft.com/}analysisSpecification"/>
 *         &lt;element name="formattedRunDuration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(namespace = "http://service.server.web.julia.juliasoft.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "analysisReportResult", propOrder = {
    "analysisSpecification",
    "formattedRunDuration"
})
public class AnalysisReportResult
    extends AnalysisResult
{

    @XmlElement(required = true)
    protected AnalysisSpecification analysisSpecification;
    protected String formattedRunDuration;

    /**
     * Gets the value of the analysisSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisSpecification }
     *     
     */
    public AnalysisSpecification getAnalysisSpecification() {
        return analysisSpecification;
    }

    /**
     * Sets the value of the analysisSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisSpecification }
     *     
     */
    public void setAnalysisSpecification(AnalysisSpecification value) {
        this.analysisSpecification = value;
    }

    /**
     * Gets the value of the formattedRunDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormattedRunDuration() {
        return formattedRunDuration;
    }

    /**
     * Sets the value of the formattedRunDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormattedRunDuration(String value) {
        this.formattedRunDuration = value;
    }

}
