//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.19 at 02:21:08 PM CET 
//


package juliawsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for juliaWarningMessageCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="juliaWarningMessageCategory">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BUG"/>
 *     &lt;enumeration value="EFFICIENCY"/>
 *     &lt;enumeration value="STYLE"/>
 *     &lt;enumeration value="UNCLASSIFIED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "juliaWarningMessageCategory")
@XmlEnum
public enum JuliaWarningMessageCategory {

    BUG,
    EFFICIENCY,
    STYLE,
    UNCLASSIFIED;

    public String value() {
        return name();
    }

    public static JuliaWarningMessageCategory fromValue(String v) {
        return valueOf(v);
    }

}
