//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.19 at 02:21:08 PM CET 
//


package juliawsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for optionable complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="optionable">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="booleanOption" type="{http://service.server.web.julia.juliasoft.com/}booleanOption"/>
 *           &lt;element name="stringOption" type="{http://service.server.web.julia.juliasoft.com/}stringOption"/>
 *           &lt;element name="intOption" type="{http://service.server.web.julia.juliasoft.com/}intOption"/>
 *           &lt;element name="setOption" type="{http://service.server.web.julia.juliasoft.com/}setOption"/>
 *           &lt;element name="enumOption" type="{http://service.server.web.julia.juliasoft.com/}enumeratedOption"/>
 *           &lt;element name="fileOption" type="{http://service.server.web.julia.juliasoft.com/}fileOption"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "optionable", propOrder = {
    "booleanOptionOrStringOptionOrIntOption"
})
@XmlSeeAlso({
    Checker.class,
    Options.class
})
public abstract class Optionable {

    @XmlElements({
        @XmlElement(name = "booleanOption", type = BooleanOption.class),
        @XmlElement(name = "stringOption", type = StringOption.class),
        @XmlElement(name = "intOption", type = IntOption.class),
        @XmlElement(name = "setOption", type = SetOption.class),
        @XmlElement(name = "enumOption", type = EnumeratedOption.class),
        @XmlElement(name = "fileOption", type = FileOption.class)
    })
    protected List<Option> booleanOptionOrStringOptionOrIntOption;

    /**
     * Gets the value of the booleanOptionOrStringOptionOrIntOption property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the booleanOptionOrStringOptionOrIntOption property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBooleanOptionOrStringOptionOrIntOption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BooleanOption }
     * {@link StringOption }
     * {@link IntOption }
     * {@link SetOption }
     * {@link EnumeratedOption }
     * {@link FileOption }
     * 
     * 
     */
    public List<Option> getBooleanOptionOrStringOptionOrIntOption() {
        if (booleanOptionOrStringOptionOrIntOption == null) {
            booleanOptionOrStringOptionOrIntOption = new ArrayList<Option>();
        }
        return this.booleanOptionOrStringOptionOrIntOption;
    }

}
